services:
  app:
    build:
      context: .
      network: host
    image: jundek:latest
    network_mode: host
    environment:
      - MODEL_PATH=/app/model/best.pt
      - RECYCLABLE_CLASSES=recyclable,可回收,plastic,glass,metal,paper,can,bottle
      # 分类聚合策略（推荐）
      - CLASS_AGGREGATION=topk_sum      # 可选：sum_all | topk_sum | top1_max | normalized_sum
      - CLASS_TOPK=5                    # topk_sum 时使用
      - CLASS_MIN_PROB=0.01             # 忽略极低概率噪声
      - DETECT_CONF=0.01                # 仅影响可视化框，不影响大类判定
      # 可选：实例标记
      - APP_TAG=compose-prod
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/__ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3