services:
  app:
    build:
      context: .
      network: host
    image: jundek:latest
    network_mode: host
    environment:
      - MODEL_PATH=/app/model/best.pt
    # 可选：覆盖默认类名映射（JSON）。示例：
    # - CLASS_ROOT_MAP={"Plastic bag":"其他垃圾","Tin can":"可回收物"}
      - DETECT_CONF=0.01                # 仅影响可视化框，不影响大类判定
      # 可选：实例标记
      - APP_TAG=compose-prod
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/__ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3